# Generated by Django 5.0.4 on 2024-05-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recomend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attraction",
            name="Latitude",
            field=models.IntegerField(blank=True, default=37.550254),
        ),
        migrations.AddField(
            model_name="attraction",
            name="Longitude",
            field=models.IntegerField(blank=True, default=127.076493),
        ),
    ]
