# Generated by Django 5.0.4 on 2024-05-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recomend", "0002_attraction_latitude_attraction_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attraction",
            name="Latitude",
            field=models.FloatField(blank=True, default=37.550254),
        ),
        migrations.AlterField(
            model_name="attraction",
            name="Longitude",
            field=models.FloatField(blank=True, default=127.076493),
        ),
    ]
