# Generated by Django 5.0.6 on 2024-05-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("content", models.TextField()),
                (
                    "menu_image",
                    models.ImageField(blank=True, upload_to="blog/images/restaurants"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=30)),
                ("content", models.TextField()),
                (
                    "photo",
                    models.ImageField(blank=True, upload_to="blog/images/restaurants"),
                ),
                ("menu", models.CharField(max_length=30)),
                ("price", models.IntegerField()),
                (
                    "menu_image",
                    models.ImageField(blank=True, upload_to="blog/images/restaurants"),
                ),
                ("tel", models.CharField(max_length=20)),
            ],
        ),
    ]
